services:
  # Base de datos local aislada en Docker
  mongodb:
    image: mongo:latest
    container_name: mi_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  # Tu red social de Node.js extraída desde Docker Hub
  mi-app:
    image: samycrafty/app:latest
    container_name: mi-app
    ports:
      - "6294:6294"
    environment:
      MONGO_URI_USERDATA: mongodb://mongodb:27017/UserData
      MONGO_URI_PLAYERCODES: mongodb://mongodb:27017/PlayerCodes
      MONGO_URI_HTMLCONTENT: mongodb://mongodb:27017/HtmlContent
      MONGO_URI_MAIL: mongodb://mongodb:27017/Mail
      MONGO_URI_MESSAGES: mongodb://mongodb:27017/Messages
      MONGO_URI_FEEDBACK: mongodb://mongodb:27017/Feedback
    depends_on:
      - mongodb
    networks:
      - app-network

  # El agente DevOps que automatiza el despliegue continuo
  watchtower:
    image: nickfedor/watchtower
    container_name: mi_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup --debug mi-app
    networks:
      - app-network

# AQUÍ ESTÁ LA CORRECCIÓN: Declaramos formalmente el volumen para Mongo
volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge